version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ca-central-1:381492185710:task-definition/test-task-front-970728:2" # 본인 Task 명
        LoadBalancerInfo:
          ContainerName: "frontend" # 본인 컨테이너 명
          ContainerPort: 80

# hooks:
#   BeforeInstall:
#     - location: scripts/stop_old_task.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/start_new_task.sh
#       timeout: 300
#       runas: root
