image:
  repository: jasonethicseo/my-frontend   # ACR 리포지토리 이름
  tag: 278d20b5beb504bd4c52a68e848df57cc2a48232

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  hostname: my-frontend.local
