image:
  repository: jasonethicseo/my-frontend   # ACR 리포지토리 이름
  tag: 6b960848de37f1b6d66eb34f8fd086ca591f9bd3

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: my-frontend.local
