image:
  repository: jasonethicseo/my-frontend   # ACR 리포지토리 이름
  tag: 5eec09fc3ece43866e23bce3c334ef21453a9121

replicaCount: 1

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
