image:
  repository: jasonethicseo/my-frontend   # ACR 리포지토리 이름
  tag: b07165da1543ea9c0ad803588cc7d7a5b54c9f2f

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: my-frontend.local
