image:
  repository: jasonethicseo/my-frontend   # ACR 리포지토리 이름
  tag: 30a7fe268f2a1e3f14965e39b906443b8740350c

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: my-frontend.local
