name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: my-frontend
      IMAGE_TAG: ${{ github.sha }}
      HELM_CHART_PATH: charts/my-frontend
      DOCKER_IMAGE: jasonethicseo/my-frontend   # Docker Hub 이미지 이름 (예: jasonethicseo/vue-frontend)
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE:$IMAGE_TAG

      - name: Update Kubernetes manifests with new image
        run: |
          sed -i "s|tag: .*|tag: $IMAGE_TAG|g" $HELM_CHART_PATH/values.yaml

      - name: Commit and push updated manifests
        run: |
          git config user.email "github-actions[bot]"
          git config user.name "github-actions[bot]@users.noreply.github.com"
          git add $HELM_CHART_PATH/values.yaml
          git commit -m "chore: update image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/jasonethicseo/frontend2.git test || echo "No changes to push"
##